name: Test apps

on:
  push:
    branches: [main]

jobs:
  test-apps:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x, 21.x, 22.x]
        app: [mongodb]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: cd ${{ matrix.app }} && npm ci

      - name: Run Tests
        run: cd ${{ matrix.app }} && npm test