name: Test apps

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  mongodb:
    defaults:
      run:
        working-directory: mongodb
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-22.04-arm, ubuntu-24.04-arm, windows-11-arm, windows-2022, windows-2025, macos-14, macos-15, macos-15-intel, macos-26]
        node-version: [18.x, 19.x, 20.x, 21.x, 22.x, 23.x, 24.x]
        #Node.js does not support Windows on ARM until 19.x
        exclude:
          - node-version: 18.x
            os: windows-11-arm
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm ci

      - name: Run Tests
        run: npm test

  sequelize:
    defaults:
      run:
        working-directory: sequelize
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-22.04-arm, ubuntu-24.04-arm, windows-11-arm, windows-2022, windows-2025, macos-14, macos-15, macos-15-intel, macos-26]
        node-version: [18.x, 19.x, 20.x, 21.x, 22.x, 23.x, 24.x]
        #Node.js does not support Windows on ARM until 19.x
        exclude:
          - node-version: 18.x
            os: windows-11-arm
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm ci

      - name: Run Tests
        run: npm test

  mysql:
    defaults:
      run:
        working-directory: mysql
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-22.04-arm, ubuntu-24.04-arm, windows-11-arm, windows-2022, windows-2025, macos-14, macos-15, macos-15-intel, macos-26]
        node-version: [18.x, 19.x, 20.x, 21.x, 22.x, 23.x, 24.x]
        #Node.js does not support Windows on ARM until 19.x
        exclude:
          - node-version: 18.x
            os: windows-11-arm
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm ci

      - name: Run Tests
        run: npm test
