name: Test apps

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-apps:
    strategy:
      fail-fast: false
      matrix:
        app: [mongodb, sequelize, mysql]
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-24.04-arm, windows-2019, windows-2022, macos-13, macos-14, macos-15]
        node-version: [16.6.0, 16.x, 17.0.0, 17.x, 18.x, 19.x, 20.x, 21.x, 22.x, 23.x]
        exclude:
          - app: mongodb
            node-version: 16.6.0
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: cd ${{ matrix.app }} && npm ci

      - name: Run Tests
        run: cd ${{ matrix.app }} && npm test
